#### Adding SSH banner ####
#- name: RHEL -> Adding SSH banner
#  lineinfile:
#    dest: /etc/ssh/sshd_config 
#    regexp: "^#?Banner none"
#    line: "Banner /etc/issue.net"
#    state: present
#  notify:
#    - restart sshd

#### Adding SSH banner ####
- name: RHEL -> Adding SSH banner
  block:
    - name: RHEL -> Banner - Check for duplicate values from {{ ssh_config_file }}
      lineinfile:
        path: "{{ ssh_config_file }}"
        create: false
        regexp: (?i)^\s*Banner\s+
        state: absent
      check_mode: true
      changed_when: false
      register: banner_dupes

    - name: RHEL -> Banner - Deduplicate values from {{ ssh_config_file }}
      lineinfile:
        path: "{{ ssh_config_file }}"
        create: false
        regexp: (?i)^\s*Banner\s+
        state: absent
      when: banner_dupes.found is defined and banner_dupes.found > 1

    - name: RHEL -> Banner - Insert correct line to {{ ssh_config_file }}
      lineinfile:
        path: "{{ ssh_config_file }}"
        create: true
        regexp: (?i)^\s*Banner\s+
        line: Banner {{ ssh_banner_file }}
        state: present
        insertbefore: ^[#\s]*Match
        validate: /usr/sbin/sshd -t -f %s
#
#### Update issue.net - Banner message ####
- name: RHEL -> Copy ssh banner file {{ ssh_banner_file }}
  template: 
    src: ssh-banner.j2 
    dest: "{{ ssh_banner_file }}"
    owner: root
    group: root
    mode: '0644'
#