#- name: RHEL -> Define a limit for password attempts
#  lineinfile:
#    dest: /etc/ssh/sshd_config 
#    regexp: "^#?MaxAuthTries 6"
#    line: "MaxAuthTries 3"
#    state: present
#  notify:
#    - restart sshd

#### Define a limit for password attempts ####
- name: RHEL -> Define a limit for password attempts
  block:
    - name: RHEL -> Password Attempts - Check for duplicate values from {{ ssh_config_file }}
      lineinfile:
        path: "{{ ssh_config_file }}"
        create: false
        regexp: (?i)^\s*MaxAuthTries\s+
        state: absent
      check_mode: true
      changed_when: false
      register: maxauth_dupes

    - name: RHEL -> Password Attempts - Deduplicate values from {{ ssh_config_file }}
      lineinfile:
        path: "{{ ssh_config_file }}"
        create: false
        regexp: (?i)^\s*MaxAuthTries\s+
        state: absent
      when: maxauth_dupes.found is defined and maxauth_dupes.found > 1

    - name: RHEL -> Password Attempts - Insert correct line to {{ ssh_config_file }}
      lineinfile:
        path: "{{ ssh_config_file }}"
        create: true
        regexp: (?i)^\s*MaxAuthTries\s+
        line: MaxAuthTries {{ ssh_pass_attempts }}
        state: present
        insertbefore: ^[#\s]*Match
        validate: /usr/sbin/sshd -t -f %s
#