#- name: RHEL -> Disable SSH Root Login
#  lineinfile: 
#    dest: /etc/ssh/sshd_config 
#    regexp: "^PermitRootLogin" 
#    line: "PermitRootLogin no" 
#    state: present
    #backup: yes
#  notify:
#    - restart sshd

#### Disable Root Login over SSH ####
- name: RHEL -> Disable SSH Root Login
  block:
    - name: RHEL -> Root Login - Check for duplicate values from {{ ssh_config_file }}
      lineinfile:
        path: "{{ ssh_config_file }}"
        create: false
        regexp: (?i)^\s*PermitRootLogin\s+
        state: absent
      check_mode: true
      changed_when: false
      register: root_login_dupes

    - name: RHEL -> Root Login - Deduplicate values from {{ ssh_config_file }}
      lineinfile:
        path: "{{ ssh_config_file }}"
        create: false
        regexp: (?i)^\s*PermitRootLogin\s+
        state: absent
      when: root_login_dupes.found is defined and root_login_dupes.found > 1

    - name: RHEL -> Root Login - Insert correct line to {{ ssh_config_file }}
      lineinfile:
        path: "{{ ssh_config_file }}"
        create: true
        regexp: (?i)^\s*PermitRootLogin\s+
        line: PermitRootLogin no
        state: present
        insertbefore: ^[#\s]*Match
        validate: /usr/sbin/sshd -t -f %s
#