#### Preventing /etc/passwd and /etc/shadow accidental deletion ###
- name: RHEL -> Prevent accidental deletion/editing - /etc/passwd and /etc/shadow
  command: chattr +i {{ item }}
  with_items:
    - /etc/passwd
    - /etc/shadow
#### Preventing /etc/passwd and /etc/shadow accidental deletion ###
#
#### Set time for terminating an idle session ####
- name: RHEL -> Set time for terminating an idle session
  copy:
    src: tmout.sh
    dest: /etc/profile.d/tmout.sh
    owner: root
    group: root
    mode: '0644'
#### Set time for terminating an idle session ####
#
