#### Backup the sshd_config ####
- name: RHEL -> Backup the sshd_config 
  copy:
    src: /etc/ssh/sshd_config 
    dest: /etc/ssh/sshd_config_{{ ansible_date_time.date }}_{{ ansible_date_time.time }}
    remote_src: yes
#
- name: Import ssh banner task
  import_tasks: ssh/banner.yml
#
- name: Import ssh idle task
  import_tasks: ssh/idle.yml
#
- name: Import root login task
  import_tasks: ssh/root_login.yml
#
- name: Import password_attempt task
  import_tasks: ssh/password_attempt.yml
#

  




  