- name: Backup the sshd_config 
  copy:
    src: /etc/ssh/sshd_config 
    dest: /etc/ssh/sshd_config_{{ ansible_date_time.date }}_{{ ansible_date_time.time }}
    remote_src: yes

- name: Adding SSH banner
  lineinfile:
    dest: /etc/ssh/sshd_config 
    regexp: "^#?Banner none"
    line: "Banner /etc/issue.net"
    state: present
  notify:
    - restart sshd

- name: Update ssh banner
  template: 
    src: ssh-banner.j2 
    dest: /etc/issue.net
    owner: root
    group: root
    mode: '0644'

- name: Define a limit for password attempts
  lineinfile:
    dest: /etc/ssh/sshd_config 
    regexp: "^#?MaxAuthTries 6"
    line: "MaxAuthTries 3"
    state: present
  notify:
    - restart sshd
  
- name: Disable root login over SSH
  lineinfile: 
    dest: /etc/ssh/sshd_config 
    regexp: "^PermitRootLogin" 
    line: "PermitRootLogin no" 
    state: present
    #backup: yes
  notify:
    - restart sshd

- name: Set SSH idle timeout interval 
  lineinfile: 
    dest: /etc/ssh/sshd_config 
    regexp: "^#ClientAliveInterval" 
    line: "ClientAliveInterval 600" 
    state: present
    #backup: yes
  notify:
    - restart sshd
  